# Pandas


# import libraries

In [3]:
import pandas as pd 
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# Check pandas version 

In [4]:
print(pd.__version__)

1.4.2


# Create empty series

In [5]:
a=pd.Series()
a

Series([], dtype: float64)

# Create series from numpy array

In [6]:
a=np.array([11,12,13,4,5,61,71])
v=pd.Series(a)
v

0    11
1    12
2    13
3     4
4     5
5    61
6    71
dtype: int32

In [7]:
a

array([11, 12, 13,  4,  5, 61, 71])

In [7]:
type(a)

numpy.ndarray

In [8]:
type(v)

pandas.core.series.Series

# Create series from list

In [9]:
s=pd.Series([1,2,3],index=['a','b','c'])
s

a    1
b    2
c    3
dtype: int64

In [10]:
s1=pd.Series([1,2,3])
s1

0    1
1    2
2    3
dtype: int64

# Modifying index

In [11]:
v

0    11
1    12
2    13
3     4
4     5
5    61
6    71
dtype: int32

In [12]:
v.index=['a','b','c','d','e','f','g']
v

a    11
b    12
c    13
d     4
e     5
f    61
g    71
dtype: int32

# create series using random and range function


In [14]:
v1=np.random.random(12)
v1

array([0.06669157, 0.76003291, 0.49398844, 0.92859482, 0.45993545,
       0.03024713, 0.92630976, 0.26512016, 0.06343299, 0.90282421,
       0.10463064, 0.63733494])

In [20]:
v2=np.arange(2,14)
v2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [18]:
s1=pd.Series(v1,v2)
s1

2     0.066692
3     0.760033
4     0.493988
5     0.928595
6     0.459935
7     0.030247
8     0.926310
9     0.265120
10    0.063433
11    0.902824
12    0.104631
13    0.637335
dtype: float64

# create series from dictionary 

In [22]:
d={'a':10,'b':20,'c':3,'d':40}
s1=pd.Series(d)
s1

a    10
b    20
c     3
d    40
dtype: int64

# create series from Scalar

In [23]:
pd.Series(34,index=[10,11,12,13])

10    34
11    34
12    34
13    34
dtype: int64

In [24]:
pd.Series(45)

0    45
dtype: int64